### ISSUE TITLE
QDateTime Error

### ISSUE THREAD

**Issue by karatemir** [spel-uchile/Pypredict#1]
Hi,

Trying to run `python -m pypredict` gives the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/pypredict/__main__.py", line 49, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/pypredict/__main__.py", line 44, in main
    application = ApplicationWindow(Sats=Sats)
  File "/usr/local/lib/python3.10/dist-packages/pypredict/app.py", line 78, in __init__
    self.updateTime()
  File "/usr/local/lib/python3.10/dist-packages/pypredict/app.py", line 533, in updateTime
    qdt = QtCore.QDateTime(self.date.year,self.date.month,self.date.day,
TypeError: arguments did not match any overloaded call:
  QDateTime(): too many arguments
  QDateTime(Union[QDateTime, datetime.datetime]): argument 1 has unexpected type 'int'
  QDateTime(Union[QDate, datetime.date]): argument 1 has unexpected type 'int'
  QDateTime(Union[QDate, datetime.date], Union[QTime, datetime.time], timeSpec: Qt.TimeSpec = Qt.LocalTime): argument 1 has unexpected type 'int'
  QDateTime(int, int, int, int, int, second: int = 0, msec: int = 0, timeSpec: int = 0): argument 6 has unexpected type 'float'
  QDateTime(Union[QDate, datetime.date], Union[QTime, datetime.time], Qt.TimeSpec, int): argument 1 has unexpected type 'int'
  QDateTime(Union[QDate, datetime.date], Union[QTime, datetime.time], QTimeZone): argument 1 has unexpected type 'int'
```

Seconds is calculated as `seconds = self.date.second + self.date.microsecond*0.000001` and I guess it ends up being a float instead of an int which is the format `QDateTime` expects. I fixed the error by wrapping it in an `int()` call. FYI

**Comment by matvidal** [comment]
Hi, thank you for your input.
I fixed the error in c284eab .
